name: PlayerLogger
version: ${project.version}
author: obfuscatedgenerated
main: ml.obfuscatedgenerated.PlayerLogger.PlayerLogger
api-version: 1.17
commands:
  getplayerlog:
    description: Gets the player log.
    usage: /<command>
    permission: PlayerLogger.get
  flushplayerlog:
    description: Add a flush point to the player log (to only show logs after it)
    usage: /<command>
    permission: PlayerLogger.flush