name: PlayerLogger
description: A Bukkit plugin to allow operators to view the joining and leaving of players without needing to access the server files.
version: ${project.version}
author: obfuscatedgenerated
main: ml.obfuscatedgenerated.PlayerLogger.PlayerLogger
api-version: 1.13
commands:
  getplayerlog:
    description: Gets the PlayerLog.
    usage: /<command>
  flushplayerlog:
    description: Adds a flush point to the PlayerLog (to only show logs after it).
    usage: /<command>
permissions:
  PlayerLogger.*:
    description: Grants all PlayerLogger permissions.
    children:
      PlayerLogger.get: true
      PlayerLogger.flush: true
  PlayerLogger.get:
    description: Allows player to read the PlayerLog.
    default: op
  PlayerLogger.flush:
    description: Allows player to add a flush point to the PlayerLog.
    default: op