name: PlayerLogger
version: 0.1.4
author: obfuscatedgenerated
main: ml.obfuscatedgenerated.PlayerLogger.PlayerLogger
api-version: 1.17
commands:
  getplayerlog:
    description: Gets the player log.
    usage: /<command>
    permission: PlayerLogger.getplayerlog